#!/usr/bin/env python3
import sys
import os
import subprocess
sys.path.append(os.path.abspath("../"))
from setup import _CONFIG as cfg
name = cfg['name']
def main():
   print("Running tests...")
   cmd = """pytest --html="docs/build/html/report.html" --verbose"""
   out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
   print(out.stdout.decode("utf-8"))
   print("Regenerating docs...")
   cmd = f"""cd docs && sphinx-apidoc -o "source/" "src/{name}" && make html"""
   out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
   print("Documentation updated.")

if __name__ == '__main__':
    main()
