#!/usr/bin/env python3
import sys
import os
import subprocess
sys.path.append(os.path.abspath("../"))

def main():
   print("Running tests...")
   cmd = """cd .. & pytest --html="docs/build/html/report.html" --verbose"""
   out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
   print(out.stdout.decode("utf-8"))
   print("Regenerating docs...")
   cmd = """sphinx-apidoc -o "../docs/source/" "../src/*" """
   out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
   cmd = "cd ../docs && make html"
   out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
   print("Documentation updated.")

if __name__ == '__main__':
    main()
